"""empty message

Revision ID: a1a676b0cdfa
Revises: a5cffa318ac2
Create Date: 2026-02-01 11:41:15.864378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1a676b0cdfa'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('age', sa.String(length=20), nullable=False),
    sa.Column('ocupation', sa.String(length=50), nullable=False),
    sa.Column('image', sa.String(length=200), nullable=False),
    sa.Column('phrases', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('town', sa.String(length=20), nullable=False),
    sa.Column('image', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites',
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('characters', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['characters'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], )
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=20), nullable=False))
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('name')

    op.drop_table('favorites')
    op.drop_table('locations')
    op.drop_table('characters')
    # ### end Alembic commands ###
