"""empty message

Revision ID: f4def737a08c
Revises: 8c517e4e29e0
Create Date: 2026-02-04 10:48:42.192026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4def737a08c'
down_revision = '8c517e4e29e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favoritesCharacters',
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('characters', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['characters'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], )
    )
    op.create_table('favoritesLocations',
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('locations', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['locations'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], )
    )
    op.drop_table('favorites')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('characters', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['characters'], ['characters.id'], name='favorites_characters_fkey'),
    sa.ForeignKeyConstraint(['user'], ['user.id'], name='favorites_user_fkey')
    )
    op.drop_table('favoritesLocations')
    op.drop_table('favoritesCharacters')
    # ### end Alembic commands ###
